# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true

    pagination_factory:
        class: AppBundle\Pagination\PaginationFactory
        arguments: ['@router']

    app.twig_extension:
           class: AppBundle\Twig\ConvertExtension
           public: false
           arguments: ['@kernel',"@translator"]
           tags:
               - { name: twig.extension }